export type GalleryImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
  orientation: 'portrait' | 'landscape' | 'square';
};

export const GALLERY_IMAGES: GalleryImage[] = [
  { src: '/images/gallery-extra/herder-with-lasso-by-river.jpg', alt: 'Herder holding a lasso on horseback beside the river below the mountains', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/expedition-originals/ger-sunrise-original.jpg', alt: 'Ger at sunrise in the valley', width: 1600, height: 1066, orientation: 'landscape' },
  { src: '/images/gallery-extra/yak-milking-at-sunrise.jpg', alt: 'Milking the yaks in the corral at sunrise, with gers on the ridge behind', width: 1500, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/horseman-galloping-through-the-river.jpg', alt: 'A horseman galloping through the river in a burst of spray below autumn rock', width: 2000, height: 1334, orientation: 'landscape' },
  { src: '/images/gallery-extra/host-family-children-on-the-summer-steppe.jpg', alt: 'Four of the host family children together on the summer steppe at golden hour', width: 2000, height: 1333, orientation: 'landscape' },
  { src: '/images/gallery-extra/guest-riding-across-the-open-plain.jpg', alt: 'A guest on horseback crossing the open plain', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gallery-extra/riding-single-file-through-the-forest.jpg', alt: 'Riding single file through the forest', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gallery-extra/rider-rearing-horse-wide.jpg', alt: 'Rider on a rearing horse against the sky', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/ger-camp-in-the-morning-mist.jpg', alt: 'The ger camp along the treeline in morning mist, horses grazing on the frost', width: 2000, height: 1125, orientation: 'landscape' },
  { src: '/images/gallery-extra/swimming-in-the-eight-lakes.jpg', alt: 'A guest wading into one of the Eight Lakes', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gallery-extra/riding-behind-the-group-in-the-larch.jpg', alt: 'Riding behind the group along a wet trail through the larch', width: 1125, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/young-horseman-in-deel.jpg', alt: 'Young horseman in a green deel astride his horse at dusk', width: 1333, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/guest-on-horseback-in-the-evening-sun.jpg', alt: 'A guest laughing on horseback in the evening sun', width: 1500, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/horse-ears-above-the-river-valley.jpg', alt: 'View between a horse’s ears down to a river winding through the autumn valley', width: 1294, height: 2300, orientation: 'portrait' },
  { src: '/images/eagle-portrait-original.jpg', alt: 'Close portrait of a Mongolian eagle', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/gallery-extra/horses-grazing-storm-monochrome.jpg', alt: 'Two horses grazing on the open steppe under heavy storm cloud, in black and white', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/crossing-the-river-with-the-camp-dog.jpg', alt: 'Riding across the river through the larch with the camp dog following', width: 1125, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/resting-against-the-horses-mane-monochrome.jpg', alt: 'Resting against a horse’s mane in the corral, a yak calf alongside, in black and white', width: 2000, height: 1333, orientation: 'landscape' },
  { src: '/images/gallery-extra/horses-in-rocky-larch-forest.jpg', alt: 'Horses grazing among boulders in the larch forest', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/guide.jpg', alt: 'Suma, local horseman and guide', width: 1152, height: 2048, orientation: 'portrait' },
  { src: '/images/gallery-extra/sewing-in-the-ger.jpg', alt: 'A host sewing on a treadle machine inside the ger', width: 1500, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/leading-the-pack-horse-below-the-cliffs.jpg', alt: 'A rider leading a loaded pack horse along the valley track below the cliffs', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gallery-extra/horseman-portrait-on-the-ridge.jpg', alt: 'A horseman in a deel on his horse above the valley', width: 1333, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/suma-rifle-mountain-portrait.jpg', alt: 'Suma resting beside a rifle above the mountain valley', width: 864, height: 1152, orientation: 'portrait' },
  { src: '/images/gallery-extra/three-men-in-deels-below-the-green-hills.jpg', alt: 'Three men of the host family in traditional deels and hats below the green hills', width: 2000, height: 1333, orientation: 'landscape' },
  { src: '/images/gallery-extra/resting-with-the-horses-in-the-shade.jpg', alt: 'Resting in the shade while the horses graze', width: 2000, height: 1333, orientation: 'landscape' },
  { src: '/images/gallery-extra/rider-in-motion-monochrome.jpg', alt: 'Rider guiding a horse, caught mid-motion in black and white', width: 1334, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/horses-and-child-by-lake.jpg', alt: 'Child walking past horses beside the lake', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/gallery-extra/eagle-feather-on-the-steppe.jpg', alt: 'An eagle feather held up against the open steppe', width: 1500, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/orkhon-waterfall-from-the-rim.jpg', alt: 'The Orkhon waterfall dropping into its pool, seen from the rock rim above', width: 1152, height: 2048, orientation: 'portrait' },
  { src: '/images/gallery-extra/horse-in-the-mist-below-the-low-sun.jpg', alt: 'A horse grazing in morning mist below the low sun, the camp behind', width: 2000, height: 1125, orientation: 'landscape' },
  { src: '/images/gallery-extra/packed-horses-rain-camp.jpg', alt: 'Packed horses waiting under storm clouds', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/van-and-rainbow-on-the-steppe.jpg', alt: 'The van on the steppe track under a rainbow', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gallery-extra/lichen-rocks-autumn-ridge.jpg', alt: 'Lichen-covered rocks and autumn grass on a high ridge', width: 2000, height: 1125, orientation: 'landscape' },
  { src: '/images/family.jpg', alt: 'Host family life in the valley', width: 1140, height: 822, orientation: 'landscape' },
  { src: '/images/guide-horse-portrait.jpg', alt: 'Suma standing with his horse on the open steppe', width: 997, height: 1496, orientation: 'portrait' },
  { src: '/images/gallery-extra/mother-and-child-in-deels.jpg', alt: 'Mother and small child in traditional deels beside the ger', width: 1333, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/horses-in-forest-rain.jpg', alt: 'Pack horses resting in the forest rain', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/guest-and-host-women-in-deels.jpg', alt: 'A guest and her host in traditional deels below the green hills', width: 2000, height: 1333, orientation: 'landscape' },
  { src: '/images/gallery-extra/guest-looking-back-mid-river-crossing.jpg', alt: 'A guest looking back from the saddle while her horse stands in the river', width: 1125, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/pack-train-on-forest-trail-rain.jpg', alt: 'Rider leading the pack train along a wet forest trail in the rain', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/gallery-extra/horseback-storm-valley-pov.jpg', alt: 'Horseback point of view riding into a stormy mountain valley', width: 1152, height: 864, orientation: 'landscape' },
  { src: '/images/gallery-extra/three-generations-in-deels.jpg', alt: 'Three generations of the host family in traditional deels below the hills', width: 2000, height: 1333, orientation: 'landscape' },
  { src: '/images/gallery-extra/riders-at-the-river-below-the-cliffs.jpg', alt: 'Riders crossing the river below rocky cliffs', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gallery-extra/horseman-on-his-dark-horse-monochrome.jpg', alt: 'A horseman in a deel and hat mounted on his dark horse, in black and white', width: 1333, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/white-yak-calf-portrait-monochrome.jpg', alt: 'Close portrait of a white yak calf in the corral, in black and white', width: 2000, height: 1333, orientation: 'landscape' },
  { src: '/images/gallery-extra/looking-out-over-the-valley-in-the-rain.jpg', alt: 'Looking out over the valley in the rain, the horse waiting alongside', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/expedition-originals/ger-and-van-camp-wide.jpg', alt: 'Ger and van camp beneath the mountains', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/packhorses-grazing-by-stream.jpg', alt: 'Loaded pack horses grazing beside a mountain stream under blue sky', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/expedition-originals/layered-hills-sunset-wide.jpg', alt: 'Layered hills at sunset', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/clouds-below-the-ridge.jpg', alt: 'Cloud lying below the ridge over forested valleys', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gallery-extra/tent-at-blue-hour.jpg', alt: 'A lit tent on the steppe at blue hour', width: 2000, height: 1498, orientation: 'landscape' },
  { src: '/images/gallery-extra/riders-climbing-the-green-hillside.jpg', alt: 'Riders climbing a green hillside under heavy cloud', width: 1125, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/corral-morning-monochrome.jpg', alt: 'Saddling up at the corral in the morning light, in black and white', width: 1333, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/group-riding-through-the-larch-meadow.jpg', alt: 'The group riding through a larch meadow full of wildflowers', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gallery-extra/rain-jacket-valley-view.jpg', alt: 'Rain jacket view across the valley', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/guest-and-guide-in-the-rain.jpg', alt: 'A guest in rain gear and the guide in a deel on the open steppe under heavy cloud', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/expedition-originals/grazing-horse-river-sun-portrait.jpg', alt: 'Horse grazing beside a sunlit river', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/testimonial-fin-bennet-host.jpg', alt: 'Fin and his Mongolian host in traditional deels on the steppe', width: 724, height: 1086, orientation: 'portrait' },
  { src: '/images/gallery-extra/horse-ears-on-the-sunlit-larch-trail.jpg', alt: 'Following the rider ahead along a sunlit larch trail, seen between a horse’s ears', width: 1294, height: 2300, orientation: 'portrait' },
  { src: '/images/expedition-originals/river-horseman-silhouette-portrait.jpg', alt: 'Horseman silhouetted beside the river', width: 1036, height: 1439, orientation: 'portrait' },
  { src: '/images/gallery-extra/leading-the-horses-through-the-larch.jpg', alt: 'Leading the horses on foot through the larch forest', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gallery-extra/autumn-river-gorge-below-the-hills.jpg', alt: 'The river running through the gorge below golden hills, autumn larch and red scrub on the rim', width: 1152, height: 2048, orientation: 'portrait' },
  { src: '/images/expedition-originals/mountain-sunset-river-wide.jpg', alt: 'Mountain sunset above a winding river', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/herder-motorbike-valley-dusk.jpg', alt: 'Herder in a deel loading his motorbike above the valley at dusk', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/gallery-extra/horseman-at-ease-on-his-dark-horse-monochrome.jpg', alt: 'A horseman at ease in the saddle of his dark horse, in black and white', width: 1333, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/herder-on-a-motorbike-above-the-valleys.jpg', alt: 'A herder on a motorbike pausing on a ridge above the green valleys', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/guest-with-the-camp-dog.jpg', alt: 'A guest lying on the grass with the camp dog', width: 1500, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/horseman-under-larch-trees.jpg', alt: 'Horseman under larch trees', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/expedition-originals/ger-blue-hour-original.jpg', alt: 'Ger at blue hour beneath the mountains', width: 1600, height: 1066, orientation: 'landscape' },
  { src: '/images/gallery-extra/herder-leading-horse-at-corral.jpg', alt: 'A herder leading a saddled horse out of the corral', width: 1333, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/lake-and-islands-through-the-pines.jpg', alt: 'One of the Eight Lakes and its wooded islands seen through the pines', width: 1125, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/horseman-with-saddled-horse-film.jpg', alt: 'Horseman in a deel and straw hat beside his saddled horse, shot on film', width: 1944, height: 1277, orientation: 'landscape' },
  { src: '/images/gallery-extra/driving-the-herd-below-the-hills-monochrome.jpg', alt: 'Herders driving the horse herd across the open hills at low sun, in black and white', width: 2000, height: 1333, orientation: 'landscape' },
  { src: '/images/gallery-extra/guide-in-red-deel-on-the-forest-trail.jpg', alt: 'The guide in a red deel riding ahead on a forest trail', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gallery-extra/ger-with-rainbow-after-rain.jpg', alt: 'A ger on the steppe with a rainbow after rain', width: 1500, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/hosts-father-and-son-in-deels.jpg', alt: 'Father and son in dark deels with orange sashes on the summer steppe', width: 1333, height: 2000, orientation: 'portrait' },
  { src: '/images/expedition-originals/suma-river-crossing-original.jpg', alt: 'Suma riding through a shallow river crossing', width: 1200, height: 1600, orientation: 'portrait' },
  { src: '/images/gallery-extra/buuz-dumplings-in-the-steamer.jpg', alt: 'Hand-folded buuz dumplings in the steamer', width: 1500, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/rider-mountain-clouds.jpg', alt: 'Rider and horse below mountain clouds', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/expedition-originals/motorbike-valley-dusk-portrait.jpg', alt: 'Motorbike above the valley at dusk', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/lake.jpg', alt: 'Eight Lakes valley and water', width: 1200, height: 1600, orientation: 'portrait' },
  { src: '/images/gers2.jpg', alt: 'White gers spread across open grassland below the mountains', width: 1152, height: 864, orientation: 'landscape' },
  { src: '/images/rob-riding-horse.jpg', alt: 'Robert riding a horse across the Mongolian valley', width: 923, height: 1600, orientation: 'portrait' },
  { src: '/images/gallery-extra/riding-across-the-golden-steppe.jpg', alt: 'Riding across the golden autumn steppe below bare hills', width: 1125, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/horse-ears-above-the-clouds.jpg', alt: 'View between a horse\u2019s ears from a ridge above the clouds', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gallery-extra/herder-with-motorbike.jpg', alt: 'Herder resting on his motorbike on the steppe at dusk', width: 2000, height: 1333, orientation: 'landscape' },
  { src: '/images/expedition-originals/rider-storm-valley-panorama-portrait.jpg', alt: 'Horseback point of view crossing a grassy Mongolian valley under storm clouds', width: 864, height: 1152, orientation: 'portrait' },
  { src: '/images/gallery-extra/guests-on-horseback-in-deels.jpg', alt: 'Two guests in borrowed deels on horseback in the evening light', width: 2000, height: 1333, orientation: 'landscape' },
  { src: '/images/gallery-extra/rider-silhouette-at-dusk-film.jpg', alt: 'Rider silhouetted on horseback against a pale dusk sky', width: 1944, height: 1277, orientation: 'landscape' },
  { src: '/images/gallery-extra/rider-in-larch-forest-rain.jpg', alt: 'Rider wrapped against the rain on horseback in the larch forest', width: 2048, height: 1366, orientation: 'landscape' },
  { src: '/images/gallery-extra/motorbike-on-the-ridge-monochrome.jpg', alt: 'Rider pausing on a motorbike to look out across the ridgelines', width: 1333, height: 2000, orientation: 'portrait' },
  { src: '/images/gallery-extra/orkhon-valley-sunburst-panorama.jpg', alt: 'Sunburst over the Orkhon Valley river bends after rain', width: 1800, height: 1013, orientation: 'landscape' },
  { src: '/images/gallery-extra/host-on-horseback-at-dusk.jpg', alt: 'Host in a black deel mounted on his horse as the light drops', width: 2000, height: 1333, orientation: 'landscape' },
  { src: '/images/expedition-originals/yaks-river-backlit-portrait.jpg', alt: 'Yaks grazing beside the river in backlit evening sun', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/gallery-extra/herder-on-a-motorbike-on-the-ridge.jpg', alt: 'A herder pausing on his motorbike on the ridge', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gallery-extra/saddling-up-above-the-green-hills.jpg', alt: 'Checking the saddle on a ridge above green hills', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gallery-extra/ger-and-land-cruiser-rain.jpg', alt: 'Ger and Land Cruiser in the rain', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/gallery-extra/guide-and-herder-on-the-trail.jpg', alt: 'The guide on horseback meeting a herder on a motorbike in the valley', width: 2000, height: 1222, orientation: 'landscape' },
]
